name: Build and Deploy

env:
  DOTNET_VERSION: '6.0.x'  

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore dependencies
        run: dotnet restore ./src/WebApplication1/WebApplication1.csproj
      
      - name: Build with dotnet
        run: dotnet build ./src/WebApplication1/WebApplication1.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./src/WebApplication1/WebApplication1.csproj -c Release -o ./src/WebApplication1/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: WebApplication1
          path: ./src/WebApplication1/publish/**
          if-no-files-found: error
          
  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Development'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v2
          with:
            name: WebApplication1
            path: WebApplication1

        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{secrets.MJR143001APP_AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.MJR143001APP_AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: WebApplication1
            
        - name: Update app settings
          uses: azure/appservice-settings@v1
          with:
            app-name: ${{secrets.MJR143001APP_AZURE_WEBAPP_NAME }}
            app-settings-json: '[{ "name": "AzureAdB2C:Instance", "value": "${{ secrets.AZUREADB2C_INSTANCE }}", "slotSetting": false }]'
